"""
Notification Service for the JobBridge application.

Provides:
  - send_email()      — renders a Jinja2 HTML template and sends via Flask-Mail (Gmail SMTP)
  - send_otp_email()  — convenience wrapper for OTP-related emails
  - send_inapp()      — inserts notification record + emits Socket.io event to user's room
  - notify()          — calls both send_inapp and send_email
"""

from __future__ import annotations

import logging
from typing import Any

from flask import current_app, render_template
from flask_mail import Message

from app.extensions import get_supabase, mail, socketio

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Email delivery
# ---------------------------------------------------------------------------

_OTP_PURPOSE_SUBJECTS: dict[str, str] = {
    "registration": "Verify your JobBridge account",
    "password_reset": "Reset your JobBridge password",
}


def send_email(
    to_email: str,
    subject: str,
    template: str,
    context: dict[str, Any],
) -> None:
    """Render a Jinja2 HTML email template and send it via Flask-Mail.

    The template is resolved from ``app/templates/email/{template}.html``.
    A plain-text fallback is generated by stripping HTML tags from the
    rendered body so that email clients without HTML support still receive
    readable content.

    Args:
        to_email:  Recipient email address.
        subject:   Email subject line.
        template:  Template filename *without* the ``.html`` extension,
                   relative to ``app/templates/email/``.
                   Example: ``"otp_verification"``
        context:   Dictionary of variables passed to the Jinja2 template.

    Raises:
        Exception: Re-raises any Flask-Mail / SMTP exception after logging.
    """
    try:
        html_body = render_template(f"email/{template}.html", **context)
    except Exception as exc:
        logger.error(
            "Failed to render email template '%s': %s", template, exc, exc_info=True
        )
        raise

    msg = Message(
        subject=subject,
        recipients=[to_email],
        html=html_body,
        sender=current_app.config.get("MAIL_DEFAULT_SENDER"),
    )

    try:
        mail.send(msg)
        logger.info("Email sent to %s | subject: %s", to_email, subject)
    except Exception as exc:
        logger.error(
            "Failed to send email to %s | subject: %s | error: %s",
            to_email,
            subject,
            exc,
            exc_info=True,
        )
        raise


def send_otp_email(to_email: str, otp: str, purpose: str) -> None:
    """Convenience wrapper that sends an OTP email for registration or password reset.

    Selects the appropriate subject line and template based on ``purpose``.

    Args:
        to_email: Recipient email address.
        otp:      The 6-digit OTP string to include in the email.
        purpose:  One of ``'registration'`` or ``'password_reset'``.

    Raises:
        ValueError: If ``purpose`` is not a recognised value.
        Exception:  Propagates any send failure from ``send_email()``.
    """
    if purpose not in _OTP_PURPOSE_SUBJECTS:
        raise ValueError(
            f"Unknown OTP purpose '{purpose}'. "
            f"Expected one of: {list(_OTP_PURPOSE_SUBJECTS.keys())}"
        )

    subject = _OTP_PURPOSE_SUBJECTS[purpose]
    template = "otp_verification" if purpose == "registration" else "password_reset"

    context: dict[str, Any] = {
        "otp": otp,
        "purpose": purpose,
        "expiry_minutes": 10,
    }

    send_email(to_email=to_email, subject=subject, template=template, context=context)


# ---------------------------------------------------------------------------
# In-app notifications (stub — completed in Task 8.1)
# ---------------------------------------------------------------------------


def send_inapp(user_id: str, event_type: str, payload: dict[str, Any]) -> None:
    """Insert a notification record and emit a Socket.io event to the user's room."""
    title = payload.get("title", "JobBridge notification")
    body = payload.get("body", "")

    try:
        supabase = get_supabase()
        supabase.table("notifications").insert(
            {
                "user_id": user_id,
                "event_type": event_type,
                "title": title,
                "body": body,
                "payload": payload,
                "is_read": False,
            }
        ).execute()
    except Exception as exc:
        logger.error("Failed to insert notification: %s", exc, exc_info=True)

    try:
        socketio.emit(event_type, payload, room=f"user_{user_id}")
    except Exception as exc:
        logger.debug("Socket.io emit skipped: %s", exc)


def notify(
    user_id: str,
    event_type: str,
    payload: dict[str, Any],
    email_context: dict[str, Any],
) -> None:
    """Deliver both an in-app notification and an email to the specified user.

    TODO (Task 8.1): Implement fully once send_inapp is complete.
      Steps to implement:
        1. Call ``send_inapp(user_id, event_type, payload)`` to deliver the
           real-time in-app notification.
        2. Resolve the user's email address from the ``users`` table via
           supabase-py using ``user_id``.
        3. Call ``send_email(to_email, subject, template, context)`` using
           values from ``email_context`` (expected keys: ``to_email``,
           ``subject``, ``template``, ``context``).

    Args:
        user_id:       UUID string of the target user.
        event_type:    Socket.io event name forwarded to ``send_inapp``.
        payload:       Event payload forwarded to ``send_inapp``.
        email_context: Dict with keys ``to_email``, ``subject``, ``template``,
                       and ``context`` forwarded to ``send_email``.
    """
    # TODO (Task 8.1): Call send_inapp(user_id, event_type, payload).
    # TODO (Task 8.1): Resolve user email and call send_email with email_context.
    logger.debug(
        "[notify stub] user_id=%s event_type=%s email_context=%s",
        user_id,
        event_type,
        email_context,
    )
