import {
  LayoutDashboard,
  User,
  Building2,
  Briefcase,
  ClipboardList,
  Calendar,
  PartyPopper,
  GraduationCap,
  Wrench,
  Globe,
  Bell,
  Settings,
  Users,
  Eye,
  BarChart3,
  Megaphone,
  Shield,
  UserCog,
  FileText,
} from 'lucide-react'
import { JOBSEEKER, EMPLOYER, STAFF, ADMIN } from './modulePaths'

export const ROLE_NAV = {
  jobseeker: [
    { to: JOBSEEKER.dashboard, label: 'Dashboard', icon: LayoutDashboard },
    { to: JOBSEEKER.profile, label: 'My Profile', icon: User },
    { to: JOBSEEKER.jobs, label: 'Job Search', icon: Briefcase },
    { to: JOBSEEKER.applications, label: 'My Applications', icon: ClipboardList },
    { to: JOBSEEKER.employment, label: 'Employment Monitoring', icon: Eye },
    { to: JOBSEEKER.interviews, label: 'Interview Schedule', icon: Calendar },
    { to: JOBSEEKER.jobFairs, label: 'Job Fair', icon: PartyPopper },
    { to: JOBSEEKER.spes, label: 'SPES', icon: GraduationCap },
    { to: JOBSEEKER.manpowerSkills, label: 'Manpower Skills Training', icon: Wrench },
    { to: JOBSEEKER.dilp, label: 'DILP', icon: FileText },
    { to: JOBSEEKER.owwa, label: 'OWWA', icon: Globe },
    { to: JOBSEEKER.notifications, label: 'Notifications', icon: Bell },
    { to: JOBSEEKER.settings, label: 'Settings', icon: Settings },
  ],
  employer: [
    { to: EMPLOYER.dashboard, label: 'Dashboard', icon: LayoutDashboard },
    { to: EMPLOYER.myProfile, label: 'My Profile', icon: User },
    { to: EMPLOYER.company, label: 'Company Profile', icon: Building2 },
    { to: EMPLOYER.vacancies, label: 'Vacancy Management', icon: Briefcase },
    { to: EMPLOYER.applicants, label: 'Applicant Management', icon: Users },
    { to: EMPLOYER.interviews, label: 'Interview Management', icon: Calendar },
    { to: EMPLOYER.jobFairs, label: 'Job Fair', icon: PartyPopper },
    { to: EMPLOYER.employment, label: 'Employment Monitoring', icon: Eye },
    { to: EMPLOYER.notifications, label: 'Notifications', icon: Bell },
    { to: EMPLOYER.settings, label: 'Settings', icon: Settings },
  ],
  staff: [
    { to: STAFF.dashboard, label: 'Dashboard', icon: LayoutDashboard },
    { to: STAFF.jobseekers, label: 'Jobseeker Management', icon: Users },
    { to: STAFF.employers, label: 'Employer Management', icon: Building2 },
    { to: STAFF.vacancies, label: 'Job Vacancy Management', icon: Briefcase },
    { to: STAFF.interviews, label: 'Interview Oversight', icon: Calendar },
    { to: STAFF.employment, label: 'Employment Monitoring', icon: Eye },
    { to: STAFF.jobFairs, label: 'Job Fair Management', icon: PartyPopper },
    { to: STAFF.manpowerSkills, label: 'Manpower Skills Management', icon: Wrench },
    { to: STAFF.dilp, label: 'DILP Management', icon: FileText },
    { to: STAFF.owwa, label: 'OWWA Management', icon: Globe },
    { to: STAFF.spes, label: 'SPES Management', icon: GraduationCap },
    { to: STAFF.lmiReports, label: 'LMI Reports', icon: BarChart3 },
    { to: STAFF.announcements, label: 'Announcements', icon: Megaphone },
    { to: STAFF.notifications, label: 'Notifications', icon: Bell },
    { to: STAFF.settings, label: 'Settings', icon: Settings },
  ],
  admin: [
    { to: ADMIN.dashboard, label: 'Dashboard', icon: LayoutDashboard },
    { to: ADMIN.jobseekers, label: 'Jobseeker Management', icon: Users },
    { to: ADMIN.employers, label: 'Employer Management', icon: Building2 },
    { to: ADMIN.staff, label: 'Staff Management', icon: UserCog },
    { to: ADMIN.vacancies, label: 'Job Vacancy Management', icon: Briefcase },
    { to: ADMIN.interviews, label: 'Interview Oversight', icon: Calendar },
    { to: ADMIN.employment, label: 'Employment Monitoring', icon: Eye },
    { to: ADMIN.jobFairs, label: 'Job Fair Management', icon: PartyPopper },
    { to: ADMIN.manpowerSkills, label: 'Manpower Skills Management', icon: Wrench },
    { to: ADMIN.dilp, label: 'DILP Management', icon: FileText },
    { to: ADMIN.owwa, label: 'OWWA Management', icon: Globe },
    { to: ADMIN.spes, label: 'SPES Management', icon: GraduationCap },
    { to: ADMIN.lmiReports, label: 'LMI Reports', icon: BarChart3 },
    { to: ADMIN.announcements, label: 'Announcements', icon: Megaphone },
    { to: ADMIN.auditTrail, label: 'Audit Trail', icon: Shield },
    { to: ADMIN.notifications, label: 'Notifications', icon: Bell },
    { to: ADMIN.settings, label: 'Settings', icon: Settings },
  ],
}
