"""
schemas package — Marshmallow 3.x serialization schemas for all JobBridge models.

All schemas are manually written (not auto-generated by marshmallow-sqlalchemy)
to give full control over field-level validation, dump_only / load_only
semantics, and nested JSONB structures.

Usage example::

    from app.schemas import UserSchema, JobseekerProfileSchema

    user_schema = UserSchema()
    result = user_schema.dump(user_obj)
    # → { "id": "...", "email": "...", "role": "...", ... }
    # password_hash is never included in the output.
"""

from app.schemas.audit_trail_schema import AuditTrailSchema
from app.schemas.employer_profile_schema import EmployerProfileSchema
from app.schemas.employment_record_schema import EmploymentRecordSchema
from app.schemas.interview_schema import InterviewSchema
from app.schemas.job_application_schema import JobApplicationSchema
from app.schemas.job_fair_attendance_schema import JobFairAttendanceSchema
from app.schemas.job_fair_registration_schema import JobFairRegistrationSchema
from app.schemas.job_fair_schema import JobFairSchema
from app.schemas.job_vacancy_schema import JobVacancySchema
from app.schemas.jobseeker_profile_schema import (
    EducationSchema,
    ExperienceSchema,
    JobseekerProfileSchema,
)
from app.schemas.lmi_report_schema import LMIReportSchema
from app.schemas.notification_schema import NotificationSchema
from app.schemas.otp_token_schema import OTPTokenSchema
from app.schemas.program_application_schema import ProgramApplicationSchema
from app.schemas.program_document_schema import ProgramDocumentSchema
from app.schemas.referral_letter_schema import ReferralLetterSchema
from app.schemas.system_setting_schema import SystemSettingSchema
from app.schemas.user_schema import UserSchema

__all__ = [
    # Nested / helper schemas
    "EducationSchema",
    "ExperienceSchema",
    # Primary model schemas (alphabetical)
    "AuditTrailSchema",
    "EmployerProfileSchema",
    "EmploymentRecordSchema",
    "InterviewSchema",
    "JobApplicationSchema",
    "JobFairAttendanceSchema",
    "JobFairRegistrationSchema",
    "JobFairSchema",
    "JobVacancySchema",
    "JobseekerProfileSchema",
    "LMIReportSchema",
    "NotificationSchema",
    "OTPTokenSchema",
    "ProgramApplicationSchema",
    "ProgramDocumentSchema",
    "ReferralLetterSchema",
    "SystemSettingSchema",
    "UserSchema",
]
